### ISSUE TITLE
 Configurar o Grafana para buscar os dados armazenados no InfluxDB

### ISSUE THREAD

**Issue by analiviatorres** [Dannihercleston/Monitoramento-de-Deslizamento-de-Encostas-usando-Microcontrolador-MPU6050-MQTT-e-Grafana.#19]

**Comment by Dannihercleston** [comment]
Link:   https://www.youtube.com/watch?v=owKOcidSZgE

Video Explicativo de como Configurar o Grafana para buscar os dados armazenados no InfluxDB


![image](https://github.com/user-attachments/assets/5e0be2ab-3e97-4185-967e-4ea11a16dda2)

**Comment by Dannihercleston** [comment]
![Dashboard](https://github.com/user-attachments/assets/b347ab08-c414-4e44-9ab5-943adef3f1ad)
