### ISSUE TITLE
Garantir que o telegraf consiga capturar os dados do Mosquitto e transmiti-los para o InfluxDB.

### ISSUE THREAD

**Issue by Dannihercleston** [Dannihercleston/Monitoramento-de-Deslizamento-de-Encostas-usando-Microcontrolador-MPU6050-MQTT-e-Grafana.#23]

**Comment by analiviatorres** [comment]
**Código Telegraf** 

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false

[[inputs.mqtt_consumer]]
  servers = ["tcp://test.mosquitto.org:1883"]
  topics = ["Encostas/dados"]
  qos = 0
  connection_timeout = "30s"
  data_format = "json"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "iZLm4a-pwUWf8FrmOPFgzI0QlOAxfuly3kBtQhqaF9K7XEB5YLAdwX9Mzqn6C0h9C74_I77fmIiynFu5ZtIVPA=="
  organization = "Monitoramento de Encostas"
  bucket = "Dados"

**Comment by analiviatorres** [comment]
**Gravação do Processo de Configuração**

link: https://www.youtube.com/watch?v=S7QvTfpfP9s

![Screenshot from 2024-08-11 15-14-39](https://github.com/user-attachments/assets/4315dd17-691b-4ad8-ad87-cbac262ad501)
