### ISSUE TITLE
Construir uma maquete que simula as condições de deslocamento de encostas e realizar testes para verificar a eficácia do sistema de monitoramento, registrando os resultados obtidos.

### ISSUE THREAD

**Issue by Dannihercleston** [Dannihercleston/Monitoramento-de-Deslizamento-de-Encostas-usando-Microcontrolador-MPU6050-MQTT-e-Grafana.#25]

**Comment by msouto** [comment]
[Regra-de-Chebyshev-Uma-Introducao.pdf](https://github.com/user-attachments/files/16666838/Regra-de-Chebyshev-Uma-Introducao.pdf)
[Regra-de-Chebyshev-Uma-Introducao.pptx](https://github.com/user-attachments/files/16666840/Regra-de-Chebyshev-Uma-Introducao.pptx)

**Comment by Dannihercleston** [comment]
![IMG-20240829-WA0010.jpg](https://github.com/user-attachments/assets/bfb8daa3-1167-41d3-8c67-83edf30e69f2)

Dados filtrados com o código python

**Comment by Dannihercleston** [comment]
![IMG-20240829-WA0011.jpg](https://github.com/user-attachments/assets/ed429908-e444-413c-897c-ded325bbb9ed)

dados após uso da regra de chebyshev.

**Comment by Dannihercleston** [comment]
![IMG-20240829-WA0012.jpg](https://github.com/user-attachments/assets/3263196e-aee3-4e1c-8346-9a360d8b5e46)

dados bruto do influxdb.

**Comment by Dannihercleston** [comment]
![IMG-20240829-WA0013.jpg](https://github.com/user-attachments/assets/82da10a4-b386-4e2d-af20-c1a17cd31d27)

InfluxDB dados do MPU6050 com mais de 24h.
