### ISSUE TITLE
 Ajudar na construção da maquete, testes, e documentação.

### ISSUE THREAD

**Issue by Dannihercleston** [Dannihercleston/Monitoramento-de-Deslizamento-de-Encostas-usando-Microcontrolador-MPU6050-MQTT-e-Grafana.#27]

**Comment by analiviatorres** [comment]
Artigo que pode ser usado como base para as metricas do sensor:

https://www.researchgate.net/profile/Verdi-Yasin/publication/379828321_DISASTER_CONTROL_SYSTEM_FOR_LANDSLIDES_USING_SUGENO_FUZZY_ALGORITHM/links/661d22b839e7641c0bcabb63/DISASTER-CONTROL-SYSTEM-FOR-LANDSLIDES-USING-SUGENO-FUZZY-ALGORITHM.pdf

**Comment by analiviatorres** [comment]
**Materias que foram usados para a construção da maquete:**

**Pilha 9V para o sensor e microcontrolador**
<img src="https://github.com/user-attachments/assets/7ab81fd9-dc73-4894-90f8-27453290acc2" alt="bateria9v" width="300"/>

**Suporte para o protoboard e microcontrolador**
<img src="https://github.com/user-attachments/assets/37c11fec-f17d-4a83-a617-ffc464878abf" alt="bateria9v" width="300"/>

**Conduite**
<img src="https://github.com/user-attachments/assets/36a9ecf7-80eb-4931-860b-451de0a5bca4" alt="bateria9v" width="300"/>

**Fita Isolante**
<img src="https://github.com/user-attachments/assets/6b096bed-0ac9-4b45-bdee-ae6051f331d8" alt="bateria9v" width="300"/>

**Jumpers**
<img src="https://github.com/user-attachments/assets/6922468c-e60d-4d1f-9810-2c7aa4c25c00" alt="bateria9v" width="300"/>

**Imagens da Maquete montada**

<img src="https://github.com/user-attachments/assets/778e82da-78f9-4a3d-b765-fd86ed5cefd6" alt="bateria9v" width="300"/>

<img src="https://github.com/user-attachments/assets/4d7e9194-0814-4aba-8b50-db9fa35619ae" alt="bateria9v" width="300"/>
