### ISSUE TITLE
Configurar o Mosquitto para funcionar localmente

### ISSUE THREAD

**Issue by analiviatorres** [Dannihercleston/Monitoramento-de-Deslizamento-de-Encostas-usando-Microcontrolador-MPU6050-MQTT-e-Grafana.#31]

**Comment by Dannihercleston** [comment]
código modificado do arduino. 

#include <Wire.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_MPU6050.h>
#include <WiFi.h>
#include <PubSubClient.h>

// as credenciais da rede WiFi
const char* ssid = "";
const char* password = "";

//  informações do broker MQTT local
const char* mqtt_server = "192.168.11.102";  // o IP local 
const int mqtt_port = 1883;

WiFiClient espClient;
PubSubClient client(espClient);

// Sensor MPU6050
Adafruit_MPU6050 mpu;
sensors_event_t a, g, temp;

// Variáveis para dados do sensor
float aceleracaoX, aceleracaoY, aceleracaoZ;
float giroscopioX, giroscopioY, giroscopioZ;
float temperatura;

// Intervalo de publicação de dados (ajuste para a frequência desejada em tempo real)
const long intervalo = 1500;  // Enviar dados a cada 20 milissegundos (50 Hz)

void configurar_wifi() {
  Serial.begin(115200);
  delay(10);

  Serial.print("Conectando à rede WiFi: ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi conectado");
  Serial.print("Endereço IP: ");
  Serial.println(WiFi.localIP());
}

void reconectar() {
  while (!client.connected()) {
    Serial.print("Tentando conexão MQTT...");
    if (client.connect("ClienteESP32")) {
      Serial.println("conectado");
    } else {
      Serial.print("falhou, rc=");
      Serial.print(client.state());
      Serial.println(" tentando novamente em 5 segundos");
      delay(5000);
    }
  }
}

void setup() {
  Wire.begin();

  if (!mpu.begin()) {
    Serial.println("Falha ao inicializar o sensor MPU6050");
    while (1);
  }

  configurar_wifi();
  client.setServer(mqtt_server, mqtt_port);
}

void loop() {
  if (!client.connected()) {
    reconectar();
  }
  client.loop();

  unsigned long millisAtual = millis();
  static unsigned long millisAnterior = 0;

  if (millisAtual - millisAnterior >= intervalo) {
    millisAnterior = millisAtual;

    mpu.getEvent(&a, &g, &temp);

    aceleracaoX = a.acceleration.x;
    aceleracaoY = a.acceleration.y;
    aceleracaoZ = a.acceleration.z;

    giroscopioX = g.gyro.x;
    giroscopioY = g.gyro.y;
    giroscopioZ = g.gyro.z;

    temperatura = temp.temperature;

    // Pacote de dados eficiente e publicação única para transmissão mais rápida
    char bufferDados[128];  // o tamanho do buffer conforme necessário
    sprintf(bufferDados,
            "{\"ax\":%.2f,\"ay\":%.2f,\"az\":%.2f,"
            "\"gx\":%.2f,\"gy\":%.2f,\"gz\":%.2f,"
            "\"temp\":%.2f}",
            aceleracaoX, aceleracaoY, aceleracaoZ,
            giroscopioX, giroscopioY, giroscopioZ, temperatura);

    client.publish("Encostas/dados", bufferDados);

    Serial.print("Dados enviados: ");
    Serial.println(bufferDados);
  }
}

**Comment by Dannihercleston** [comment]
código do compose.yml atualizado.
version: '3'

services:
  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mosquitto
    networks:
      - influxdb_network
      - mosquitto_network

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=Dados
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    networks:
      - influxdb_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - influxdb_network

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883"
    networks:
      - mosquitto_network
      - influxdb_network

networks:
  influxdb_network:
  mosquitto_network:

volumes:
  mosquitto_data:
  mosquitto_log:

**Comment by Dannihercleston** [comment]
código do telegraf.conf atualizado. 

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["Encostas/dados"]
  qos = 0
  connection_timeout = "30s"
  data_format = "json"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "a8Q_9SCG2IPNLUwV-UiXw6zrBG4Mv5Dqj4S51geL0Qkcu4f-w0m3JlJfXjYiQTRvg9rhdROF1i3F0FNxX54HuA=="
  organization = "Monitoramento de Encostas"
  bucket = "Dados"

**Comment by msouto** [comment]
Link correto: https://www.youtube.com/watch?v=C7INjzjSOKI
