### ISSUE TITLE
Preparação do Pitch Deck

### ISSUE THREAD

**Issue by analiviatorres** [Dannihercleston/Monitoramento-de-Deslizamento-de-Encostas-usando-Microcontrolador-MPU6050-MQTT-e-Grafana.#33]

**Comment by analiviatorres** [comment]
**Pitch Deck**

[Decky- Monitoramento de Deslizamento de Encostas usando Microcontrolador, MPU6050, MQTT e Grafana.pdf](https://github.com/user-attachments/files/16841149/Decky-.Monitoramento.de.Deslizamento.de.Encostas.usando.Microcontrolador.MPU6050.MQTT.e.Grafana.pdf)

**Comment by msouto** [comment]
Atenção para ler todas as instruções de envio constantes na tarefa do google sala de aula.

**Comment by Dannihercleston** [comment]
[Decky- Monitoramento de Deslizamento de Encostas usando Microcontrolador, MPU6050, MQTT e Grafana.pdf](https://github.com/user-attachments/files/16937212/Decky-.Monitoramento.de.Deslizamento.de.Encostas.usando.Microcontrolador.MPU6050.MQTT.e.Grafana.pdf)
